### ISSUE TITLE
Wiremock standalone 3: NoSuchMethodError

### ISSUE THREAD

**Issue by samuelstein** [wiremock/wiremock#2621]
### Proposal

After switching maven artifact group from _com.github.tomakehurst_ to _org.wiremock_ the following exception occurred:

`java.lang.NoSuchMethodError: 'void wiremock.org.eclipse.jetty.server.AbstractConnectionFactory.<init>(java.lang.String[])'`

### Reproduction steps

I'm using Spring Boot in version 3.2.2 and JUnit 5.

### References

The wiremock server is instanciated with the following annotation:
@WireMockTest(httpPort = 80)

**Comment by vdonets-dev** [comment]
Have the same trouble, is it even compatible?

**Comment by leeturner** [comment]
Hi, I am struggling to reproduce this using Spring Boot 3.2.2 and wiremock standalone 3.4.2.  Do you have an example project that demonstrates this or more details of the tests you are running to help me diagnose the issue?

**Comment by leeturner** [comment]
Hi, we are planning on releasing `3.6.0` this week if possible.  If you could come back with any additional information we might be able to look into this before the next release.

**Comment by samuelstein** [comment]
With Spring boot 3.2.5, Java 21 and wiremock-standalone in version 3.5.4 the problem still exists in my project

**Comment by savinov** [comment]
@leeturner the example uses wiremock-jetty-12 version 3.10.0: https://github.com/wiremock/wiremock-examples/blob/main/build.gradle#L2

wiremock-jetty-12 version 3.10.0 works with SB 3.2.4, but 3.11.0 and 3.12.0 trow the error again:
`java.lang.NoSuchMethodError: 'org.apache.hc.client5.http.config.RequestConfig$Builder org.apache.hc.client5.http.config.RequestConfig$Builder.setProtocolUpgradeEnabled(boolean)'`

wiremock-standalone 3.12.0 works fine with SB 3.2.4 without any errors

**Comment by savinov** [comment]
Unfortunately I have to use SB 3.2.4
There is another error if I set httpclient5 version to 5.2.4, to match httpclient dependency of wiremock-jetty12 version 3.12.0.
`java.lang.NoSuchMethodError: 'void org.apache.hc.core5.http.impl.io.DefaultHttpRequestWriterFactory.<init>(org.apache.hc.core5.http.config.Http1Config)'`
