### ISSUE TITLE
ResponseTemplateTransformer for 3.0.0 not documented

### ISSUE THREAD

**Issue by manofthepeace** [wiremock/wiremock#2345]
### Summary

I am trying to migrate to wiremock 3.0.0 but I am stuck at pretty much step 1. I am using ResponseTemplateTransformer, and I have no idea how to make it work with 3.0.0, even with the simplest usage.

the documentation here https://wiremock.org/3.x/docs/response-templating/ uses the constructors and builder that does not exist anymore. I tried to adapt manually, but the lack of javadoc + documentation makes it near impossible, unless I am missing something obvious.

basically the following lines are the only ones that gives me compilation error that I do not know how to solve;

new ResponseTemplateTransformer(true) and
new ResponseTemplateTransformer(true, "json", Jackson2Helper.INSTANCE) (using handlebars-jackson)

the new constructor is 
```java
  public ResponseTemplateTransformer(
      TemplateEngine templateEngine,
      boolean global,
      FileSource files,
      List<TemplateModelDataProviderExtension> templateModelDataProviders)
```

Nowhere I can find what the TemplateEngine is or must be, or files, of templateModelDataProviders, nor what is nullable.

For the second case I tried to manually create the templateEngine to add the helper, but it is a nap, and not idea what is the map key, and how it will be used afterward.

Help would be appreciated.

### References

https://wiremock.org/3.x/docs/extending-wiremock/  all the TransformingResponses links points to non existing page.
https://wiremock.org/3.x/docs/response-templating/  cannot be followed as it uses the older apis.
