### ISSUE TITLE
Updating 3.4.2 -> 3.5.1 broken

### ISSUE THREAD

**Issue by edeandrea** [wiremock/wiremock#2660]
### Proposal

When updating from 3.4.2 to 3.5.1 things seem to be broken. See https://github.com/quarkusio/quarkus-super-heroes/pull/784

I'm getting these exceptions when trying to bootstrap WireMock:

```
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/thread/ThreadPool
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:107)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig(WireMockConfiguration.java:161)
	at io.quarkus.sample.superheroes.fight.HeroesVillainsNarrationWiremockServerResource.<init>(HeroesVillainsNarrationWiremockServerResource.java:18)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.thread.ThreadPool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

### Reproduction steps

1. Clone https://github.com/quarkusio/quarkus-super-heroes
2. Switch to the PR branch (`gh pr checkout 784`)
3. `cd` into `rest-fights`
4. Run `./mvnw clean verify`

### References

https://github.com/quarkusio/quarkus-super-heroes/pull/784

**Comment by cyrilc-pro** [comment]
Having the same. Getting the dependency tree with debug shows:
```
[WARNING] The POM for org.wiremock:wiremock:jar:3.5.1 is invalid, transitive dependencies (if any) will not be available: 3 problems were encountered while building the effective model for org.wiremock:wiremock:3.5.1
[ERROR] 'dependencies.dependency.version' for org.junit.platform:junit-platform-testkit:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.junit.platform:junit-platform-launcher:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-params:jar is missing. @ 
```

**Comment by reta** [comment]
Confirming the issue as well, @tomakehurst it seems like `testFixturesApi` dependencies are sneaking in into published POM file, but they should not I think, submitting a fix right away.

**Comment by tomakehurst** [comment]
Ugh, thanks for reporting. Let this be an object lesson in the perils of releasing last thing the day before a bank holiday weekend!

**Comment by tomakehurst** [comment]
3.5.2 now released with a fix.
